apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: quelpoke
spec:
  parentRefs:
  - name: gke-l7-global-external-managed  # Gateway typique GKE
  rules:
  - backendRefs:
    - name: quelpoke-service
      port: 80
