name: Build and Push Docker image  # Nom du workflow

on:
  push:
    branches:
      - main  # Ce workflow se déclenche uniquement quand on push sur la branche main

jobs:
  build:  
    runs-on: ubuntu-latest  # GitHub crée une vm Ubuntu pour exécuter les étapes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Récupère le code du repo sur la vm

      - name: Login to DockerHub
        uses: docker/login-action@v3  # Action Docker = se connecte à DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}    

      - name: Build and push
        uses: docker/build-push-action@v5  # Action Docker = build et push l'image
        with:
          context: .        
          push: true        # push image vers dockerhub
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quelpoke:latest
